---
title: Amplify Demo Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Look how fast it is

'
logo: "/assets/images/logo.jpg"
baseurl: "/amplify"
url: https://penyadap.github.io
paginate: 5
name: Your Name
bio: 'Mea suas vituperatoribus et, virtute corpora quaestio cum ut. Ne solet nostrum
  complectitur pri, vis ut inani populo.

'
author_image: "/assets/images/author.jpg"
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
- jekyll-paginate
